### ISSUE TITLE
Prevent publishing pages in fork

### ISSUE THREAD

**Issue by mkopec87** [adri0/investd#46]
Not sure if feasible, but in my fork I get failing build for main branch because of not being able to publish the page.
Maybe we can somehow prevent that?

https://github.com/mkopec87/investd/actions/runs/4188445079/jobs/7259585973

**Comment by adri0** [comment]
@mkopec87 I came across this discussion today: https://github.com/orgs/community/discussions/26704#discussioncomment-5268498

**Comment by mkopec87** [comment]
Ok, I disabled the workflow in my fork! :) Thanks :)
